jdk: openjdk8
language: java
notifications:
  slack:
    secure: zEpFwp7e5t0dnvd/BX7gFctTB7ZrZ8gFDPMy/fEAP2jaVr2QZ9QMOBaCiHCqeROUQBD6yGG44KmQ9y7YXVIRD2gVBSk8wPVBWyZy7R3ZJZSXzQc/jCWHysOXAc+7Iik5U/8ZBZDN6Nk07g6hrr0Y1b4xhB9j4mQ3g1pL1DzjQycVP1YMUbauslZkPd1vWGBaLVeehge1XeTgoxQrQKFD+MGzaWzUYQbrmXYV5kLslqC4dOotxuUZFPlZOcgg8+l5/RNNCcTnE/AHTn7L0YeZSILdS+0AI3iAzmyyjrGWB5jux+pE4mxpfLSiG4NMYp/nRjsfKSzEHDZq9C0n4yRzgwDYLRBT4jDpPVKLRg/i4pPXKOpUcTUYsh3jwiNZOmg+htkYTMVR7ryVn/b2KMUu8IRz5NtBYwZKLajfcS8SLYscwvxp1OrwGIFScUN0wGqN+My+zqDwtKZ3xNZRU8yzulo0u/HUykm1K91laiobSFA08KjFBcarBr700z8QDdtRloLokxVVZgc8nWD1aKSoLlMbQIhN0IvXgFiN42eloYM/AvSkr3llsFff+7OiZUE2aWEY26RQj6pBC2pij+6oDceKsB1rXaSBueUG7rqJW9DR1Sw5yNtDjbALYtq6LPg47JWxDVfsg/FrySswGtWmLVQ4azqftktd4rU4RSFd7m0=
deploy:
  provider: releases
  api_key:
    secure: s/qEawZaQ+QbM4d6aaHOqqC7v+bdrjU6nVQ7zOw1Xrt8niGPzByOz074zhZxxYWK/JpyWteepBvOnUbLbMsdA0m7vMaEHcrKQvMXubS7Vd17ntaQUMguggkcuo1hdcuxC0/TriuKVMU5Z34hCHpVr61/08hBjONSxhwzR1XFxuzq5kzJdO3dOA4KWAzdqYpJyO7tSnKZTC0inloZ4qtCZOZHaZGVMFZkmTD6LfpUZw92qMwjLXD9gk4exhutvCiB9scJfj1XqH6oFrEQIXr1TyqNshpLu/BB9MdybCSAM8nQBI5uFJFsFAGXOvZo/MAu02DTljeWgbPy/K6jNlAPSlBoQ0ZxR1z6GEyFYfS2PMze1Obq8eaX++RkQOzGP3WOTieJRcbdQS0fMMwDmk7DaRZ5lawZtT0TlojvidFjkEkBaHSmsvtdtRB0ovZz2k4l1YeCA9VtzTZfH8ajn2//O3KIzh4LfACGdhPm8ptg7X/4ZF7OMW2mvIpFoKn0EXOzUj0Day8S4K9LIyci1dYvgK7/Tmkp/nA1y/NU4gTB4oXXSPTVDxyFUvhNeOBSGoWCpUhH2Fi4VLO+AE2mdEEiQvtfzpJ6raWpn56OzhKONRRXYIPe+84hzAWIpYG9e/z/ft8f8O+odW3UXUXRGg/07OtEk7L+ruVxn2aH+p4VgX0=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-skytap-plugin
